Error: Consistently apply `Result<T, E>` across the codebase (#109)
* Initial impl for indexes, duplicating all data

* Attemp to store the index definition on the db

* CREATE & DROP support for indexes

* Check if a key exist in the Index

* Refactored index managment, updating index in real-time, iterating on the tuples by index

* Check exlusive acces to the database instance with file advisory lock

* Fix typos and documentation

* Partially done. Refactoring the indexes to work with DataKey & multiples transactions

* Finish refactoring of using DataKey

* Checking for duplicates

* Checking for UNIQUE violations, refactores to avoid using Mutex

* Seek function for indexes

* Index: iterator for range of keys

* Finish all the core Index support

* Fix test

* TypeValue has now relational semantics, implementing /. Adding a natural  for numbers. Removing EqTypeValue, RangeTypeValue

* Removed old EqTypeValue and merge master

* Styling & naming fixes

* Removed the use of HashSet in the BTreeIndex and use range queries instead

* Revert "TypeValue has now relational semantics, implementing /. Adding a natural  for numbers. Removing EqTypeValue, RangeTypeValue (#99)"

This reverts commit e8b398737c93b6660e78684d9bbf5f0bbcc0f793.

* Fix crash in procedural macros on BitCraftMini

* Restore typevalue, reverting revert-99-typevalue

* Restore typevalue, reverting revert-99-typevalue

* Fix crash in procedural macros on BitCraftMini

* First pass on using Result for error checking

* Adding support for using of Result on test, fix tests on Btree, Kill some .unwraps()

* Renaming Errors for better organization

* Support for DBError for Sled & RocksDb

* Fixing some leftovers .unwraps on relational db

* Fixing some leftovers .unwraps transactional/message_log

* Addressing PR comments: Rename to DBError, reporting byte size in Result

* Revert use of Results on iterators and simplify some test on index

* Fix some unwraps and use of DbError in other storage engines

* Revert "Merge branch 'index' into error"

This reverts commit f3fc8da13eb544d6a14bd8fe9d1e84f4c6159e9b, reversing
changes made to 0e064c70432e55b41b68b9a57b4b16ecb1e61a64.

* Fix test for opening the database multiple times

Co-authored-by: Ryan Daum <ryan.daum@gmail.com>
Co-authored-by: Noa <coolreader18@gmail.com>
Co-authored-by: Tyler Cloutier <cloutiertyler@aol.com>